TaskListCore.MVC/Controllers/TaskListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TaskListCore.Domain;

namespace TaskListCore.MVC.Controllers
{
    public class TaskListController : Controller
    {
        private ITaskListService _Service;

        public TaskListController(ITaskListService service)
        {
            _Service = service;
        }

        // GET: TaskList
        public ActionResult Index()
        {
            var tasklist = _Service.GetTaskListItems();
            return View(tasklist);
        }

        // GET: TaskList/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TaskList/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TaskListItem model)
        {
            if (ModelState.IsValid)
            {
                _Service.AddNewTask(model);
                return RedirectToAction("Index");
            }              
            else
            {
                return View();
            }
        }

        // GET: TaskList/Complete/5
        public ActionResult Complete(int id)
        {
            var task = _Service.GetTask(id);
            if (task.Execute())
            {
                _Service.UpdateTask(task);
            }
            return RedirectToAction("Index");
        }

        // GET: TaskList/Delete/5
        public ActionResult Delete(int id)
        {
            var task = _Service.GetTask(id);
            _Service.DeleteTask(task);
            return RedirectToAction("Index");
        } 

        public ActionResult Error()
        {
            return View();
        }

    }
}

TaskListCore.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskListCore.MVC</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="TaskList" asp-action="Index" class="navbar-brand">TaskListCore.MVC</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="TaskList" asp-action="Index">Task List</a></li>
                    <li><a asp-area="" asp-controller="TaskList" asp-action="Create">New Task</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - TaskListCore.MVC</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

TaskListCore.MVC/Views/TaskList/Create.cshtml
@model TaskListItem

@{
    ViewData["Title"] = "Create";
}

<h2>Create new task</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>        
        <div class="form-group">
            <label asp-for="Task" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Task" class="form-control" />
                <span asp-validation-for="Task" class="text-danger"></span>
            </div>
        </div>        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

TaskListCore.MVC/Views/TaskList/Index.cshtml
@model IEnumerable<TaskListItem>

@{
    ViewData["Title"] = "Index";
}

<h2>Task List</h2>

<div class="list-group">
    @foreach (var item in Model)
    {
        <div class="list-group-item@(item.Executed ? " task-completed":"")">
            @item.Task
            <a asp-action="Delete" asp-route-id="@item.Id"><span class="glyphicon glyphicon-remove" title="delete">&nbsp;</span></a>
            @if (!item.Executed)
            {
                <a asp-action="Complete" asp-route-id="@item.Id"><span class="glyphicon glyphicon-ok" title="complete" asp-action="Complete">&nbsp;</span></a>
            }
        </div>
    }
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            $('div.list-group-item a').on('click', function () { return confirm("Sure?") });
        })
    </script>
}